- RSDKv5/RSDK/Audio/Audio.cpp
- RSDKv5/RSDK/Core/RetroEngine.hpp
- RSDKv5/RSDK/Input/Input.hpp
- RSDKv5/RSDK/Input/SDL2/SDL2InputDevice.cpp
- RSDKv5/RSDK/User/Core/UserCore.cpp
This is a stripped-down version of #45, without the endian or Wii U stuff. I can try submitting the endian stuff later, once I know which method would be accepted here.
Since the last PR, I found another way to fix the `KBInputDevice.cpp` issue: `Input.hpp` already contains a partial (broken?) workaround for missing virtual key definitions, so I've just extended the workaround to support cases where some codes are defined while others aren't.
> Some fixes and a little tidying.

- RSDKv5/RSDK/Graphics/DX11/DX11RenderDevice.cpp
- RSDKv5/RSDK/Graphics/DX9/DX9RenderDevice.cpp
- RSDKv5/RSDK/Graphics/EGL/EGLRenderDevice.cpp
- RSDKv5/RSDK/Graphics/GLFW/GLFWRenderDevice.cpp
- RSDKv5/RSDK/Graphics/SDL2/SDL2RenderDevice.cpp
By default, setting maxPixWidth past 512 will cause stretching on the right side of the screen, getting worse the wider you go. This PR makes it so RSDKv5 will check for both screenWidth and maxPixHeight to determine if the texture size should be 512x256 or 1024x512, eliminating the stretching issue until you set maxPixWidth past 1024.
Default (424):
Maximum (512):
Past Maximum (576):
Past Maximum in PR:
New Maximum (1024):
New Maximum with PR:
> Fix display with maxPixWidth past 512 (up to 1024)

- RSDKv5/RSDK/Audio/SDL2/SDL2AudioDevice.cpp
- RSDKv5/RSDK/Core/RetroEngine.cpp
- RSDKv5/RSDK/Graphics/SDL2/SDL2RenderDevice.cpp
- RSDKv5/RSDK/Input/Input.cpp
- RSDKv5/RSDK/Input/SDL2/SDL2InputDevice.cpp
- RSDKv5/RSDK/Input/SDL2/SDL2InputDevice.hpp
- RSDKv5/main.cpp
Calling `SDL_Quit` twice is not guaranteed to be safe. In fact, it crashes my Wii U port.
If there's a better place to call `SDL_Init` and `SDL_Quit`, then I can move them. By the way, the SDL input backend never deinitialises. Is that something that should be addressed?
> SDL: Fix deinitialisation.

- Makefile
Extra space causes errors while linking
> Remove extra space

- RSDKv5/RSDK/Core/ModAPI.cpp
- RSDKv5/RSDK/Scene/Scene.cpp
- RSDKv5/RSDK/Storage/Storage.cpp
- RSDKv5/RSDK/Storage/Storage.hpp
- RSDKv5/RSDK/Storage/Text.cpp
I believe that this is closer to the original source code, as the previous code was rife with duplication and redundant conditions.
I've also modified the alignment so that it works correctly on platforms where the alignment requirement is larger than 4. This is achieved using a C++11 definition. Without this correction, the address sanitizer on x86-64 Linux throws a fit.
I've also renamed the 'clean storage' functions to make their differences more clear, as 'ClearEmptyStorage' and 'ClearUnusedStorage' don't get the point across very well. This can be reverted if those were actually the original names of the functions in the original source code.
By making this modification, an invalid memory access that occurs when a storage becomes full and must be cleaned is avoided. This memory …
> Improve memory allocation.

- RSDKv5/RSDK/Dev/Debug.cpp
- RSDKv5/RSDK/Graphics/SDL2/SDL2RenderDevice.cpp
- RSDKv5/RSDK/Input/SDL2/SDL2InputDevice.cpp
- RSDKv5/RSDK/Input/SDL2/SDL2InputDevice.hpp
The controller disconnection logic is bugged, causing a chain reaction that led to crazy memory corruption in my Wii U port.
I'm open to feedback about the controller heuristic: I just threw that in to see what you think.
> Controller fixes (and a little tidying).

- README.md
- RSDKv5/RSDK/Graphics/Drawing.cpp
- RSDKv5/RSDK/Graphics/SDL2/SDL2RenderDevice.cpp
- RSDKv5/RSDK/User/Dummy/DummyCore.cpp
Hi. The tweaks are just some adjustments that I made downstream, and I figured that I might as well upstream them if possible.
I'm not sure why `SDL_OpenURL` was disabled, so if there's a reason that I'm missing, I wouldn't mind leaving this as a downstream-only modification. The platform that my port runs on supports `SDL_OpenURL`, so I find it useful to have enabled.
I also added my port to the list of forks in the readme, since I think that it's more or less complete now.
> Minor tweaks, a fix, enable `SDL_OpenURL`, and add my Wii U fork to the readme.

- makefiles/Switch.cfg
The Switch port uses EGL instead of GLFW3.
> Remove GLFW3 from Switch Makefile.

- RSDKv5/RSDK/Input/SDL2/SDL2InputDevice.cpp
This allows for controller mappings to be loaded that aren't in the default SDL2 database.
> Add SDL2 controller mappings from gamecontrollerdb.txt

- RSDKv5/RSDK/Graphics/DX11/DX11RenderDevice.cpp
- RSDKv5/RSDK/Graphics/DX9/DX9RenderDevice.cpp
- RSDKv5/RSDK/Graphics/GLFW/GLFWRenderDevice.cpp
- RSDKv5/RSDK/Graphics/SDL2/SDL2RenderDevice.cpp
- RSDKv5U/RSDKv5U_vk.vcxproj
When using the F1 dev function to switch to the previous scene while on the first scene of the first category ("Presentation - Logos" in Mania Plus), instead of taking you to the last scene in the last category ("Videos - True End?" in this case) as expected, it tries to load a nonexistent scene in the Presentation category, which results in a crash:
This happens because the function doesn't check for if ``sceneInfo.listPos`` underflows after it decreases by 1, which is fixed in this pull request. Although you realistically are never going to have 256 categories consisting of 256 scenes each, I also added a check for if listPos overflows when using the F2 function.
> Fix F1/F2 dev functions not checking for listPos overflowing/underflowing

- RSDKv5/RSDK/User/Core/UserCore.cpp
This array was allocated using `new` even if the mod loader was disabled, and the size used for the allocation was never checked to be valid.
Only allocate/free when mod loader is enabled, and add a size check.
ASan on Linux showed a 1 byte leak when `gamePadCount==0`, who knows what was happening on other platforms.
> Fix gamePadMappings memory leak

- RSDKv5/RSDK/Storage/Storage.cpp
- RSDKv5/RSDK/User/Core/UserAchievements.cpp
The allocator never takes into account the size of the header when allocating a new entry.
While not in the original release, this oversight can lead to a buffer overflow.
In `UserAchievements`, local variables allocated by GetAchievementName weren't freed after use, which lead to allocation errors much later (similar to #120).
> Various memory allocation fixes

- RSDKv5/RSDK/Audio/XAudio/XAudioDevice.hpp
This fixes the warnings and errors from building with the Visual Studio solution method introduced in [481464a](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/7718f7c6864ce19b73937d7aced6a4be76f344a1).
> Add preprocessor checks for GCC pragmas

- makefiles/Linux.cfg
The issue was the failure to build due to PortAudio not being linked at all.
> Fixed PortAudio linking error in Linux Makefile

- RSDKv5/RSDK/Graphics/Drawing.cpp
- RSDKv5/RSDK/Input/RawInput/RawInputDevice.cpp
Back in 481464a, some code for unused parts of the engine were commented out to give ports for weaker hardware a slight performance boost. Sincethis was original code, this commit uncomments it and instead ifdefs it behind RETRO_USE_ORIGINAL_CODE being enabled.
> Ifdef out unused code instead of commenting it

- RSDKv5/RSDK/Graphics/GLFW/GLFWRenderDevice.cpp
Currently, the GLFW backend doesn't take into account if vsync is enabled or not, and makes no calls to `glfwSwapInterval`.
> call glfwSwapInterval in SetupRendering to enable/disable vsync

- RSDKv5/RSDK/Core/ModAPI.cpp
Check for modList size before trying to access its elements.
Iterate backwards to find the last active mod in the list.
Fixes #205.
> Fix crash on mod loading

- RSDKv5/RSDK/Core/Legacy/v3/RetroEnginev3.cpp
- RSDKv5/RSDK/Core/Legacy/v4/RetroEnginev4.cpp
These were missing from v5U compared to the standalone decomps.
> Add dev menu/title screen/reload button commands in legacy script error screens

- RSDKv5/RSDK/Core/ModAPI.cpp
- RSDKv5/RSDK/Core/RetroEngine.cpp
Free the main mod.ini dictionary whenever the mod isn't active. Rename most ini dictionaries to use different variable names, which makes this part of the code less confusing (each of them were using `ini`).
Free some temporary char buffers.
Whenever the mod loader is enabled, void* are replaced with std::function
in the ObjectClass struct, which makes this a non-POD struct.
Using memset on it corrupts the vtables, which leads to memory leaks later on.
Manually zero-initialize this list instead when the mod loader is enabled.
> ModAPI: Fix some more memory leaks

- RSDKv5/RSDK/Core/Legacy/v3/RetroEnginev3.cpp
The `LoadXMLSoundFX` function for Legacy v3 Mode was trying to look for both the `name` and `path` fields in the gameXML file. Although the mod loader does give v3 SFX "names", they aren't supposed to be set via gameXML; only `path` should exist.
> Fix v3 GameXML SoundFX

- RSDKv5/RSDK/Core/Legacy/v3/RetroEnginev3.cpp
- RSDKv5/RSDK/Core/Legacy/v3/RetroEnginev3.hpp
- RSDKv5/RSDK/Core/Legacy/v4/RetroEnginev4.cpp
- RSDKv5/RSDK/Core/Legacy/v4/RetroEnginev4.hpp
- RSDKv5/RSDK/Core/RetroEngine.cpp
- RSDKv5/RSDK/Core/RetroEngine.hpp
- RSDKv5/RSDK/Scene/Legacy/v3/ScriptLegacyv3.cpp
- RSDKv5/RSDK/Scene/Legacy/v4/ScriptLegacyv4.cpp
- RSDKv5/RSDK/Storage/Legacy/UserStorageLegacy.cpp
- RSDKv5/RSDK/User/Dummy/DummyCore.hpp
- android/app/src/main/java/org/rems/rsdkv5/Launcher.java
- Added a check to set `game.hasPlusDLC` based on the `RSDK_AUTOBUILD` flag in v4 (and v3 if the mod loader is enabled)
- Added the ability to set the game title through game.xml (works in all versions)
- Updated the v3 RetroEngineCallback and v4 NotifyCallback ID lists and callbacks
- Overloading the script var count in v4 now throws a script error in-game instead of printing a warning in the log (this was also added for the alias count in v3)
- The `engine.standalone` global variable is now forced to 0 in v3/v4 when the mod loader is enabled
This PR doesn't include the Origins Plus collision/hitbox stuff as I don't know if Leonx254 wants to make his own PR for that
> Parity changes between standalone v3/v4 decomps and v5U

- RSDKv5/RSDK/Audio/Legacy/AudioLegacy.cpp
- RSDKv5/RSDK/Core/ModAPI.cpp
- RSDKv5/RSDK/Core/ModAPI.hpp
- RSDKv5/RSDK/Graphics/Sprite.cpp
- RSDKv5/RSDK/User/Core/UserAchievements.cpp
Hoping to fix most of the remaining ModAPI issues and improve performance a bit. Fix some remaining decomp inaccuracies as well.
**ModAPI:**
- - [X] Use const ref on most parameters to avoid unnecessary copies
- ~~Investigate crash on Wii when loading SSZ2M ---> seems to be `ModInfo` related, sort of mitigated by not sorting mods?~~ Out of scope.
Other fixes:
- - [X] AudioLegacy: Fix potential out of bounds channel access (`channelID == 0x10`)
- - [X] Revert "UserAchievements: Free local variables" (invalid free which would also end up triggering a bug)
- - [X] LoadImage: Fix memory leak (image.palette getting assigned to NULL, preventing deallocation)
- - [X] LoadSpritesheet: Check for failed allocation (fix TMP allocation workaround when STG is full)
- ~~Investigate 3DS crash on exit …
> Misc fixes and improvements

- README.md
- dependencies/android/README.md
- dependencies/ogl/.gitignore
- dependencies/ogl/README.md
- dependencies/windows/.gitignore
- dependencies/windows/README.md
This carries over some of the improvements to the CMake documentation/building instructions made in the RSDKv3 and RSDKv4 repositories, and generally cleans up some minor things.
> CMake documentation improvements

- RSDKv5/RSDK/Graphics/EGL/EGLRenderDevice.cpp
- RSDKv5/RSDK/Graphics/GLFW/GLFWRenderDevice.cpp
Avoids stack use after free errors in ASan.
> GLFW/EGL: Free file buffers after shader compilation

- RSDKv5/RSDK/Storage/Legacy/UserStorageLegacy.cpp
Fixes v4 NOTIFY_DEBUGPRINT crashing when called via CallNativeFunction2 on builds compiled without MVSC
> Fix v4 NOTIFY_DEBUGPRINT

- RSDKv5/RSDK/User/Steam/SteamAchievements.hpp
At some point the name got moved to inside an AchievementID structure, so check that value instead.
> Fix compiler error for Steam configuration

- RSDKv5/RSDK/Core/Legacy/v3/RetroEnginev3.cpp
- RSDKv5/RSDK/Core/Legacy/v4/RetroEnginev4.cpp
- RSDKv5/RSDK/Core/ModAPI.cpp
- RSDKv5/RSDK/Core/ModAPI.hpp
- RSDKv5/RSDK/Core/RetroEngine.cpp
- RSDKv5/RSDK/Core/RetroEngine.hpp
- RSDKv5/RSDK/Dev/Debug.cpp
- RSDKv5/RSDK/Dev/Debug.hpp
- RSDKv5/RSDK/Scene/Legacy/v3/ScriptLegacyv3.cpp
- RSDKv5/RSDK/Scene/Legacy/v4/ScriptLegacyv4.cpp
- RSDKv5/RSDK/Scene/Scene.cpp
- RSDKv5/RSDK/Scene/Scene.hpp
Adds a custom character select for v5's dev menu in ModAPI v3, based on the one for the legacy modes and a proof of concept by Jd. Characters can be added via `AddDevMenuCharacter` or game.xml, and the active dev menu character can be retrieved via `GetActiveDevMenuCharacter`. In addition, pressing Start while highlighting Stage Select in the Dev Menu will skip the player select and let you keep your current character instead, in case you need a specific character combo.
playerListPos is `-1` whenever a dev menu character is not active. Active dev menu characters are only kept until the next scene load, in which case it'll be set to `-1`.
Also added `GetChannelAttributes`, which gets the volume, panning, and speed of a channel.
Other changes:
- Added sanity checks to replacing the game …
> Add v5 dev menu character select and GetChannelAttributes to ModAPI v3
